In [15]:
# Pour manipuler efficacement des tables de données dans Python
import pandas as pd

# Pour faire des requêtes GET et POST
import requests

# Gestion des temps
import datetime as dt
    
g = requests.get("https://data.angers.fr/api/records/1.0/search/",
        params={
                'dataset': 'bus-tram-position-tr',
                'rows': 500
                })

#Pour tester que tout a bien fonctionnné, on va vérifié le statut.
g.raise_for_status()

#Si ça dit rien c'est que c'est bon :) Dans le doute, regardons le statut...
g.status_code

#Il y a aussi un décodeur JSON, si on sait que la réponse est dans ce format. Du coup, il parse le JSON et rend un dictionnaire !
g.json()


dd = g.json()['records']
    
#Arret
id_arret = [elem['fields']['idarret'] for elem in dd]
nom_arret = [elem['fields']['nomarret'] for elem in dd]
mne_arret = [elem['fields']['mnemoarret'] for elem in dd]

arret = pd.DataFrame({
    'id_arret': id_arret,
    'nom_arret': nom_arret,
    'mne_arret': mne_arret
})

#arret.info()

arret

#Bus
id_vh = [elem['fields']['idvh'] for elem in dd]
type_vh = [elem['fields']['type'] for elem in dd]
etat_vh = [elem['fields']['etat'] for elem in dd]

bus = pd.DataFrame({
    'id_vh': id_vh,
    'type_vh': type_vh,
    'etat_vh': etat_vh
})

#bus.info()

bus

#Ligne
id_ligne = [elem['fields']['idligne'] for elem in dd]
nom_ligne = [elem['fields']['nomligne'] for elem in dd]
mne_ligne = [elem['fields']['mnemoligne'] for elem in dd]

ligne = pd.DataFrame({
    'id_ligne': id_arret,
    'nom_ligne': nom_ligne,
    'mne_ligne': mne_ligne
})

#ligne.info()

ligne

#Trajet
id_bus = [elem['fields']['idvh'] for elem in dd]
id_ligne = [elem['fields']['idligne'] for elem in dd]
latitude = [elem['fields']['coordonnees'][0] for elem in dd]
longitude = [elem['fields']['coordonnees'][1] for elem in dd]

trajet = pd.DataFrame({
    'id_bus': id_bus,
    'id_ligne': id_ligne,
    'latitude': latitude,
    'longitude': longitude
})

#trajet.info()

trajet

#Etape
id_arret = [elem['fields']['idarret'] for elem in dd]
harret = [elem['fields']['harret'] for elem in dd]
record_timestamp = [elem['record_timestamp'] for elem in dd]
ecart = [elem['fields']['ecart'] for elem in dd]

etape = pd.DataFrame({
    'id_arret': id_arret,
    'heure_theorique': harret,
    'ecart': ecart,
    'record_timestamp': record_timestamp
})

etape['record_timestamp'] = pd.to_datetime(etape['record_timestamp'])

def transfo(row):
    return row['record_timestamp'] + dt.timedelta(seconds=row['ecart'])
etape['heure_estime'] = etape.apply(transfo, axis='columns')

#etape.info()

etape

,ecart,heure_theorique,id_arret,record_timestamp,heure_estime
0,0,2018-06-19T06:53:55+00:00,671973,2018-06-19 06:57:17,2018-06-19 06:57:17
1,0,2018-06-19T07:09:46+00:00,671375,2018-06-19 07:16:13,2018-06-19 07:16:13
2,0,2018-06-19T07:26:00+00:00,671375,2018-06-19 07:31:18,2018-06-19 07:31:18
3,0,2018-06-19T07:45:09+00:00,671973,2018-06-19 07:57:53,2018-06-19 07:57:53
4,0,2018-06-19T09:09:00+00:00,671963,2018-06-19 08:56:54,2018-06-19 08:56:54
5,0,2018-06-19T09:14:00+00:00,671784,2018-06-19 09:00:58,2018-06-19 09:00:58
6,11421,2018-06-19T09:09:21+00:00,672699,2018-06-19 09:03:17,2018-06-19 12:13:38
7,204,2018-06-19T09:03:24+00:00,671841,2018-06-19 09:03:17,2018-06-19 09:06:41
8,30,2018-06-19T09:03:31+00:00,671999,2018-06-19 09:03:17,2018-06-19 09:03:47
9,327,2018-06-19T09:03:01+00:00,671897,2018-06-19 09:03:17,2018-06-19 09:08:44
10,151,2018-06-19T09:05:45+00:00,671733,2018-06-19 09:03:17,2018-06-19 09:05:48
11,-7,2018-06-19T09:03:46+00:00,671698,2018-06-19 09:03:17,2018-06-19 09:03:10
12,154,2018-06-19T09:04:53+00:00,671489,2018-06-19 09:03:17,2018-06-19 09:05:51
13,654,2018-06-19T09:03:10+00:00,671753,2018-06-19 09:03:17,2018-06-19 09:14:11
14,532,2018-06-19T09:04:32+00:00,671862,2018-06-19 09:03:17,2018-06-19 09:12:09
15,-100,2018-06-19T09:03:44+00:00,671559,2018-06-19 09:03:17,2018-06-19 09:01:37
16,244,2018-06-19T09:03:14+00:00,671693,2018-06-19 09:03:17,2018-06-19 09:07:21
17,248,2018-06-19T09:03:49+00:00,671436,2018-06-19 09:03:17,2018-06-19 09:07:25
18,-108,2018-06-19T09:03:35+00:00,671892,2018-06-19 09:03:17,2018-06-19 09:01:29
19,337,2018-06-19T09:03:11+00:00,671260,2018-06-19 09:03:17,2018-06-19 09:08:54
20,210,2018-06-19T09:04:11+00:00,671579,2018-06-19 09:03:17,2018-06-19 09:06:47
21,45,2018-06-19T09:03:34+00:00,671062,2018-06-19 09:03:17,2018-06-19 09:04:02
22,24,2018-06-19T09:04:34+00:00,671059,2018-06-19 09:03:17,2018-06-19 09:03:41
23,337,2018-06-19T09:03:17+00:00,671073,2018-06-19 09:03:17,2018-06-19 09:08:54
24,25,2018-06-19T09:03:20+00:00,671765,2018-06-19 09:03:17,2018-06-19 09:03:42
25,303,2018-06-19T09:03:11+00:00,671523,2018-06-19 09:03:17,2018-06-19 09:08:20
26,430,2018-06-19T09:03:07+00:00,672637,2018-06-19 09:03:17,2018-06-19 09:10:27
27,10,2018-06-19T09:03:58+00:00,671543,2018-06-19 09:03:17,2018-06-19 09:03:27
28,238,2018-06-19T09:04:37+00:00,671465,2018-06-19 09:03:17,2018-06-19 09:07:15
29,420,2018-06-19T09:03:09+00:00,671184,2018-06-19 09:03:17,2018-06-19 09:10:17
...,...,...,...,...,...
76,45,2018-06-19T09:03:41+00:00,671601,2018-06-19 09:03:17,2018-06-19 09:04:02
77,423,2018-06-19T09:04:28+00:00,671263,2018-06-19 09:03:17,2018-06-19 09:10:20
78,5,2018-06-19T09:03:36+00:00,671700,2018-06-19 09:03:17,2018-06-19 09:03:22
79,544,2018-06-19T09:04:00+00:00,671604,2018-06-19 09:03:17,2018-06-19 09:12:21
80,102,2018-06-19T09:03:07+00:00,671959,2018-06-19 09:03:17,2018-06-19 09:04:59
81,256,2018-06-19T09:03:33+00:00,671276,2018-06-19 09:03:17,2018-06-19 09:07:33
82,102,2018-06-19T09:04:05+00:00,671513,2018-06-19 09:03:17,2018-06-19 09:04:59
83,-43,2018-06-19T09:03:17+00:00,671784,2018-06-19 09:03:17,2018-06-19 09:02:34
84,50,2018-06-19T09:03:31+00:00,671476,2018-06-19 09:03:17,2018-06-19 09:04:07
85,241,2018-06-19T09:03:40+00:00,671507,2018-06-19 09:03:17,2018-06-19 09:07:18
86,-222,2018-06-19T09:03:20+00:00,671627,2018-06-19 09:03:17,2018-06-19 08:59:35
87,51,2018-06-19T09:03:21+00:00,671074,2018-06-19 09:03:17,2018-06-19 09:04:08
88,47,2018-06-19T09:04:06+00:00,671053,2018-06-19 09:03:17,2018-06-19 09:04:04
89,159,2018-06-19T09:03:07+00:00,671266,2018-06-19 09:02:54,2018-06-19 09:05:33
90,0,2018-06-19T09:08:00+00:00,672010,2018-06-19 09:01:56,2018-06-19 09:01:56
91,0,2018-06-19T09:06:00+00:00,672502,2018-06-19 08:59:13,2018-06-19 08:59:13
92,0,2018-06-19T09:09:00+00:00,672520,2018-06-19 08:56:12,2018-06-19 08:56:12
93,0,2018-06-19T09:11:00+00:00,671154,2018-06-19 08:55:14,2018-06-19 08:55:14
94,0,2018-06-19T09:08:00+00:00,671723,2018-06-19 08:59:54,2018-06-19 08:59:54
95,0,2018-06-19T09:10:00+00:00,671785,2018-06-19 08:59:38,2018-06-19 08:59:38
96,-110,2018-06-19T09:02:50+00:00,671600,2018-06-19 09:02:54,2018-06-19 09:01:04
97,50,2018-06-19T09:03:34+00:00,672072,2018-06-19 09:03:17,2018-06-19 09:04:07
98,-117,2018-06-19T09:03:42+00:00,671716,2018-06-19 09:03:17,2018-06-19 09:01:20
99,131,2018-06-19T09:03:37+00:00,672618,2018-06-19 09:03:17,2018-06-19 09:05:28
100,309,2018-06-19T09:03:08+00:00,671489,2018-06-19 09:03:17,2018-06-19 09:08:26
101,59,2018-06-19T09:04:10+00:00,671975,2018-06-19 09:03:17,2018-06-19 09:04:16
102,122,2018-06-19T09:03:14+00:00,671437,2018-06-19 09:03:17,2018-06-19 09:05:19
103,-150,2018-06-19T09:03:20+00:00,671447,2018-06-19 09:03:17,2018-06-19 09:00:47
104,232,2018-06-19T09:03:24+00:00,671687,2018-06-19 09:03:17,2018-06-19 09:07:09
105,44,2018-06-19T09:04:43+00:00,671067,2018-06-19 09:03:17,2018-06-19 09:04:01