In [1]:
# pour les date
import datetime as dt

# Pour manipuler efficacement des tables de données dans Python
import pandas as pd

# Pour faire des requêtes GET et POST
import requests

# sql
from sqlalchemy import create_engine

In [2]:
r = requests.get("https://data.angers.fr/api/records/1.0/search/",
                 params={
                     'dataset': 'bus-tram-position-tr',
                     'rows': 10,
                     'facet':'novh',
                     'facet':'mnemoligne',
                     'facet':'nomligne',
                     'facet':'dest'
                 })

In [3]:
type(r)

requests.models.Response

In [4]:
r.status_code

200

In [5]:
# r.json()

{'facet_groups': [{'facets': [{'count': 6,
     'name': 'AVRILLE ARDENNE',
     'path': 'AVRILLE ARDENNE',
     'state': 'displayed'},
    {'count': 6,
     'name': 'BELLE BEILLE',
     'path': 'BELLE BEILLE',
     'state': 'displayed'},
    {'count': 6,
     'name': 'MONPLAISIR',
     'path': 'MONPLAISIR',
     'state': 'displayed'},
    {'count': 6,
     'name': 'ST BARTHELEMY',
     'path': 'ST BARTHELEMY',
     'state': 'displayed'},
    {'count': 5,
     'name': 'PAS EN SERVICE',
     'path': 'PAS EN SERVICE',
     'state': 'displayed'},
    {'count': 5,
     'name': 'TRELAZE QUANTINIERE',
     'path': 'TRELAZE QUANTINIERE',
     'state': 'displayed'},
    {'count': 4,
     'name': 'ANGERS ROSERAIE',
     'path': 'ANGERS ROSERAIE',
     'state': 'displayed'},
    {'count': 4,
     'name': 'CIRCULAIRE SENS A',
     'path': 'CIRCULAIRE SENS A',
     'state': 'displayed'},
    {'count': 4,
     'name': 'CIRCULAIRE SENS B',
     'path': 'CIRCULAIRE SENS B',
     'state': 'displayed'},
    {'count': 4,
     'name': 'MURS ERIGNE',
     'path': 'MURS ERIGNE',
     'state': 'displayed'},
    {'count': 4, 'name': 'ZI EST', 'path': 'ZI EST', 'state': 'displayed'},
    {'count': 3, 'name': 'BANCHAIS', 'path': 'BANCHAIS', 'state': 'displayed'},
    {'count': 3,
     'name': 'ESPACE ANJOU',
     'path': 'ESPACE ANJOU',
     'state': 'displayed'},
    {'count': 3,
     'name': "LAC DE MAINE - L'HOIRIE",
     'path': "LAC DE MAINE - L'HOIRIE",
     'state': 'displayed'},
    {'count': 3,
     'name': 'SPECIAL PISCINE',
     'path': 'SPECIAL PISCINE',
     'state': 'displayed'},
    {'count': 3,
     'name': 'ST SYLVAIN',
     'path': 'ST SYLVAIN',
     'state': 'displayed'},
    {'count': 2,
     'name': 'AQUAVITA VERNEAU',
     'path': 'AQUAVITA VERNEAU',
     'state': 'displayed'},
    {'count': 2,
     'name': 'AVRILLE ADEZIERE',
     'path': 'AVRILLE ADEZIERE',
     'state': 'displayed'},
    {'count': 2,
     'name': 'AVRILLE SALETTE',
     'path': 'AVRILLE SALETTE',
     'state': 'displayed'},
    {'count': 2,
     'name': 'BEAUCOUZE  HAUTE ROCHE',
     'path': 'BEAUCOUZE  HAUTE ROCHE',
     'state': 'displayed'},
    {'count': 2,
     'name': "BEAUCOUZE L'ATOLL",
     'path': "BEAUCOUZE L'ATOLL",
     'state': 'displayed'},
    {'count': 2,
     'name': 'BOUCHEMAINE CENTRE',
     'path': 'BOUCHEMAINE CENTRE',
     'state': 'displayed'},
    {'count': 2,
     'name': 'BOUCHEMAINE CHANTOURTEAU',
     'path': 'BOUCHEMAINE CHANTOURTEAU',
     'state': 'displayed'},
    {'count': 2,
     'name': 'CHU - HOPITAL',
     'path': 'CHU - HOPITAL',
     'state': 'displayed'},
    {'count': 2,
     'name': 'EVENTARD par MONPLAISIR',
     'path': 'EVENTARD par MONPLAISIR',
     'state': 'displayed'},
    {'count': 2,
     'name': 'MONTREUIL JUIGNE',
     'path': 'MONTREUIL JUIGNE',
     'state': 'displayed'},
    {'count': 2,
     'name': 'MOULIN MARCILLE PAR TRELA',
     'path': 'MOULIN MARCILLE PAR TRELA',
     'state': 'displayed'},
    {'count': 2,
     'name': 'SAINTE GEMMES',
     'path': 'SAINTE GEMMES',
     'state': 'displayed'},
    {'count': 2,
     'name': 'ST AUBIN LA SALLE',
     'path': 'ST AUBIN LA SALLE',
     'state': 'displayed'},
    {'count': 1,
     'name': "CLINIQUE DE L'ANJOU",
     'path': "CLINIQUE DE L'ANJOU",
     'state': 'displayed'},
    {'count': 1,
     'name': 'HAUTE DE RECULEE',
     'path': 'HAUTE DE RECULEE',
     'state': 'displayed'},
    {'count': 1,
     'name': 'MAIRIE DES PONTS DE CE',
     'path': 'MAIRIE DES PONTS DE CE',
     'state': 'displayed'},
    {'count': 1,
     'name': 'MOULIN MARCILLE',
     'path': 'MOULIN MARCILLE',
     'state': 'displayed'},
    {'count': 1,
     'name': 'POLE 49 par SCHWEITZER',
     'path': 'POLE 49 par SCHWEITZER',
     'state': 'displayed'},
    {'count': 1,
     'name': 'SCHWEITZER',
     'path': 'SCHWEITZER',
     'state': 'displayed'},
    {'count': 1, 'name': 'SORGES', 'path': 'SORGES', 'state': 'displayed'},
    {'count': 1,
     'name': 'TRELAZE ST LEZIN',
     'path': 'TRELAZE ST LEZIN',
     'state': 'displayed'},
    {'count': 1,
     'name': 'VERNUSSON PAR TRELAZE',
     'path': 'VERNUSSON PAR TRELAZE',
     'state': 'displayed'},
    {'count': 1,
     'name': 'ZI TRELAZE PAR ST LEZIN',
     'path': 'ZI TRELAZE PAR ST LEZIN',
     'state': 'displayed'}],
   'name': 'dest'}],
 'nhits': 105,
 'parameters': {'dataset': ['bus-tram-position-tr'],
  'facet': ['dest'],
  'format': 'json',
  'rows': 10,
  'timezone': 'UTC'},
 'records': [{'datasetid': 'bus-tram-position-tr',
   'fields': {'cap': 95,
    'coordonnees': [47.4956, -0.56967987],
    'dest': 'PAS EN SERVICE',
    'ecart': 0,
    'etat': 'HLPS',
    'harret': '2018-06-19T06:53:55+00:00',
    'idarret': 671973,
    'iddesserte': 268721409,
    'idligne': 268435460,
    'idparcours': 268721408,
    'idvh': 268436137,
    'mnemoarret': 'SDCTB',
    'mnemoligne': '04',
    'nomarret': 'SORTIE BUS CTB',
    'nomligne': 'BEAUCOUZE <> ST BARTHELEMY',
    'novh': '681',
    'numarret': 17220,
    'sv': '0423',
    'type': 'OmniArtE6',
    'x': 381077,
    'y': 2281381},
   'geometry': {'coordinates': [-0.56967987, 47.4956], 'type': 'Point'},
   'record_timestamp': '2018-06-19T06:57:17+00:00',
   'recordid': '14c506f09a99d91c098950a3fe823121db098640'},
  {'datasetid': 'bus-tram-position-tr',
   'fields': {'cap': 185,
    'coordonnees': [47.476323, -0.49280852],
    'dest': 'PAS EN SERVICE',
    'ecart': 0,
    'etat': 'HLPS',
    'harret': '2018-06-19T07:09:46+00:00',
    'idarret': 671375,
    'iddesserte': 268720385,
    'idligne': 268435460,
    'idparcours': 268720384,
    'idvh': 268436259,
    'mnemoarret': 'DEPOT SD',
    'mnemoligne': '04',
    'nomarret': 'SORTIE DEPOT ST BART',
    'nomligne': 'BEAUCOUZE <> ST BARTHELEMY',
    'novh': '803',
    'numarret': 6562,
    'sv': '0412',
    'type': 'OmniSTDE6',
    'x': 386788,
    'y': 2279028},
   'geometry': {'coordinates': [-0.49280852, 47.476323], 'type': 'Point'},
   'record_timestamp': '2018-06-19T07:16:13+00:00',
   'recordid': 'd2707eca39de09f79bcef7be9101e0af08c1a754'},
  {'datasetid': 'bus-tram-position-tr',
   'fields': {'cap': 5,
    'coordonnees': [47.475119, -0.49273127],
    'dest': 'PAS EN SERVICE',
    'ecart': 0,
    'etat': 'HLPS',
    'harret': '2018-06-19T07:26:00+00:00',
    'idarret': 671375,
    'iddesserte': 268875521,
    'idligne': 268435462,
    'idparcours': 268875520,
    'idvh': 268435899,
    'mnemoarret': 'DEPOT SD',
    'mnemoligne': '06',
    'nomarret': 'SORTIE DEPOT ST BART',
    'nomligne': 'BOUCHEMAINE <> Z I  EST',
    'novh': '443',
    'numarret': 6562,
    'sv': '0621',
    'type': 'OMNICITY',
    'x': 386789,
    'y': 2278894},
   'geometry': {'coordinates': [-0.49273127, 47.475119], 'type': 'Point'},
   'record_timestamp': '2018-06-19T07:31:18+00:00',
   'recordid': 'e9e06aaa63b6f1909e235bab88e3c0c22401af53'},
  {'datasetid': 'bus-tram-position-tr',
   'fields': {'cap': 95,
    'coordonnees': [47.495681, -0.56928591],
    'dest': 'PAS EN SERVICE',
    'ecart': 0,
    'etat': 'HLPS',
    'harret': '2018-06-19T07:45:09+00:00',
    'idarret': 671973,
    'iddesserte': 268525313,
    'idligne': 268435457,
    'idparcours': 268525312,
    'idvh': 268436120,
    'mnemoarret': 'SDCTB',
    'mnemoligne': '01',
    'nomarret': 'SORTIE BUS CTB',
    'nomligne': 'BELLE BEILLE <> MONPLAISIR',
    'novh': '664',
    'numarret': 17220,
    'sv': '0104',
    'type': 'OMNIART',
    'x': 381107,
    'y': 2281389},
   'geometry': {'coordinates': [-0.56928591, 47.495681], 'type': 'Point'},
   'record_timestamp': '2018-06-19T07:57:53+00:00',
   'recordid': 'a0a5b38fdf8b9abdd0ac05e7bf1854b76737021b'},
  {'datasetid': 'bus-tram-position-tr',
   'fields': {'cap': 33,
    'coordonnees': [47.433765, -0.50064398],
    'dest': 'AQUAVITA VERNEAU',
    'ecart': 0,
    'etat': 'TDEP',
    'harret': '2018-06-19T09:14:00+00:00',
    'idarret': 671784,
    'iddesserte': 268969729,
    'idligne': 268435464,
    'idparcours': 268969728,
    'idvh': 268435910,
    'mnemoarret': 'MOULINMA',
    'mnemoligne': '08',
    'nomarret': 'MOULIN MARCILLE',
    'nomligne': 'PONTS CE <>  AQUAVITA H. RECULEE',
    'novh': '454',
    'numarret': 32614,
    'sv': '0803',
    'type': 'OMNICITY',
    'x': 386027,
    'y': 2274321},
   'geometry': {'coordinates': [-0.50064398, 47.433765], 'type': 'Point'},
   'record_timestamp': '2018-06-19T09:00:58+00:00',
   'recordid': 'a627776c208afbfbfe4fcb5838046358a0b64ab9'},
  {'datasetid': 'bus-tram-position-tr',
   'fields': {'cap': 185,
    'coordonnees': [47.493159, -0.56542969],
    'dest': 'CIRCULAIRE SENS B',
    'ecart': 0,
    'etat': 'TDEP',
    'harret': '2018-06-19T09:21:00+00:00',
    'idarret': 672581,
    'iddesserte': 268807681,
    'idligne': 268435461,
    'idparcours': 268807680,
    'idvh': 268435913,
    'mnemoarret': 'AQVI-D5B',
    'mnemoligne': '05',
    'nomarret': 'AQUA VITA',
    'nomligne': 'CIRCULAIRE VERNEAU GARE EUROPE',
    'novh': '457',
    'numarret': 96211,
    'sv': '0521',
    'type': 'OMNICITY',
    'x': 381387,
    'y': 2281098},
   'geometry': {'coordinates': [-0.56542969, 47.493159], 'type': 'Point'},
   'record_timestamp': '2018-06-19T09:11:14+00:00',
   'recordid': '11f4c1b37f06116e5b390b43b8e54697d256c67d'},
  {'datasetid': 'bus-tram-position-tr',
   'fields': {'cap': 286,
    'coordonnees': [47.478642, -0.6056908],
    'dest': 'MONPLAISIR',
    'ecart': 0,
    'etat': 'TDEP',
    'harret': '2018-06-19T09:18:00+00:00',
    'idarret': 671723,
    'iddesserte': 268513025,
    'idligne': 268435457,
    'idparcours': 268513024,
    'idvh': 268436057,
    'mnemoarret': 'MATECHNO',
    'mnemoligne': '01',
    'nomarret': 'MAISON DE TECHNOPOLE',
    'nomligne': 'BELLE BEILLE <> MONPLAISIR',
    'novh': '601',
    'numarret': 29466,
    'sv': '0121',
    'type': 'MAN City',
    'x': 378295,
    'y': 2279598},
   'geometry': {'coordinates': [-0.6056908, 47.478642], 'type': 'Point'},
   'record_timestamp': '2018-06-19T09:12:13+00:00',
   'recordid': 'a1b0c279c5f0d4879ca2c32b0ea558e39a40bec6'},
  {'datasetid': 'bus-tram-position-tr',
   'fields': {'cap': 28,
    'coordonnees': [47.476644, -0.50728302],
    'dest': 'SPECIAL PISCINE',
    'ecart': -247,
    'etat': 'HL',
    'harret': '2018-06-19T09:30:00+00:00',
    'idarret': 672636,
    'iddesserte': 272302338,
    'idligne': 268435515,
    'idparcours': 272302336,
    'idvh': 268435879,
    'mnemoarret': 'P-MONPL',
    'mnemoligne': '535',
    'nomarret': 'PISCINE MONPLAISIR',
    'nomligne': 'Piscine MONPLAISIR',
    'novh': '423',
    'numarret': 804722,
    'sv': '53513',
    'type': 'OMNICITY',
    'x': 385699,
    'y': 2279103},
   'geometry': {'coordinates': [-0.50728302, 47.476644], 'type': 'Point'},
   'record_timestamp': '2018-06-19T09:13:16+00:00',
   'recordid': 'c1face88ffc04e903b88bc015a11c7192cc278ca'},
  {'datasetid': 'bus-tram-position-tr',
   'fields': {'cap': 202,
    'coordonnees': [47.472719, -0.53030476],
    'dest': 'MOULIN MARCILLE PAR TRELA',
    'ecart': 235,
    'etat': 'LIGN',
    'harret': '2018-06-19T09:13:46+00:00',
    'idarret': 671760,
    'iddesserte': 269266959,
    'idligne': 268435468,
    'idparcours': 269266944,
    'idvh': 268435905,
    'mnemoarret': 'MONTAIG',
    'mnemoligne': '12',
    'nomarret': 'MONTAIGNE',
    'nomligne': 'M-MARCILLE <> ST AUBIN LA SALLE',
    'novh': '449',
    'numarret': 11328,
    'sv': '1210',
    'type': 'OMNICITY',
    'x': 383949,
    'y': 2278730},
   'geometry': {'coordinates': [-0.53030476, 47.472719], 'type': 'Point'},
   'record_timestamp': '2018-06-19T09:13:16+00:00',
   'recordid': '330bfa9dc100be890f1ad6d996ec766cdfae6765'},
  {'datasetid': 'bus-tram-position-tr',
   'fields': {'cap': 201,
    'coordonnees': [47.452054, -0.50764243],
    'dest': 'MOULIN MARCILLE PAR TRELA',
    'ecart': 6,
    'etat': 'LIGN',
    'harret': '2018-06-19T09:14:13+00:00',
    'idarret': 671915,
    'iddesserte': 269266976,
    'idligne': 268435468,
    'idparcours': 269266944,
    'idvh': 268435909,
    'mnemoarret': 'REPTRELA',
    'mnemoligne': '12',
    'nomarret': 'REPUBLIQUE TRELAZE',
    'nomligne': 'M-MARCILLE <> ST AUBIN LA SALLE',
    'novh': '453',
    'numarret': 9180,
    'sv': '1208',
    'type': 'OMNICITY',
    'x': 385573,
    'y': 2276372},
   'geometry': {'coordinates': [-0.50764243, 47.452054], 'type': 'Point'},
   'record_timestamp': '2018-06-19T09:13:16+00:00',
   'recordid': 'c22f1921661fede0c6f6635c9e3bddf9f5d46476'}]}

In [6]:
dd = r.json(parse_int=str)['records']

In [7]:
# dd[0]

{'datasetid': 'bus-tram-position-tr',
 'fields': {'cap': '185',
  'coordonnees': [47.493159, -0.56542969],
  'dest': 'CIRCULAIRE SENS B',
  'ecart': '0',
  'etat': 'TDEP',
  'harret': '2018-06-19T09:21:00+00:00',
  'idarret': '672581',
  'iddesserte': '268807681',
  'idligne': '268435461',
  'idparcours': '268807680',
  'idvh': '268435913',
  'mnemoarret': 'AQVI-D5B',
  'mnemoligne': '05',
  'nomarret': 'AQUA VITA',
  'nomligne': 'CIRCULAIRE VERNEAU GARE EUROPE',
  'novh': '457',
  'numarret': '96211',
  'sv': '0521',
  'type': 'OMNICITY',
  'x': '381387',
  'y': '2281098'},
 'geometry': {'coordinates': [-0.56542969, 47.493159], 'type': 'Point'},
 'record_timestamp': '2018-06-19T09:11:14+00:00',
 'recordid': '11f4c1b37f06116e5b390b43b8e54697d256c67d'}

In [8]:
# récupération des données du json

#bus
idBus = [elem['fields']['idvh'] for elem in dd]
type = [elem['fields']['type'] for elem in dd]
etat = [elem['fields']['etat'] for elem in dd]

#arret
idArret = [elem['fields']['idarret'] for elem in dd]
nomarret = [elem['fields']['nomarret'] for elem in dd]

#ligne
idLigne  = [elem['fields']['idligne'] for elem in dd]
nomLigne = [elem['fields']['nomligne'] for elem in dd]
numLigne = [elem['fields']['mnemoligne'] for elem in dd]

#trajet
lats = [elem['fields']['coordonnees'][0] for elem in dd]
lons = [elem['fields']['coordonnees'][1] for elem in dd]
dest = [elem['fields']['dest'] for elem in dd]

#etape
harret = [elem['fields']['harret'] for elem in dd]
ecart = [elem['fields']['ecart'] for elem in dd]

df = pd.DataFrame({
    'idBus': idBus,
    'type': type,
    'etat': etat,
    'idArret': idArret,
    'nomarret': nomarret,
    'idLigne': idLigne,
    'nomLigne': nomLigne,
    'numLigne': numLigne,
    'lats': lats,
    'lons': lons,
    'dest': dest,
    'harret': harret,
    'ecart': ecart
})

# df

,dest,ecart,etat,harret,idArret,idBus,idLigne,lats,lons,nomLigne,nomarret,numLigne,type
0,PAS EN SERVICE,0,HLPS,2018-06-19T06:53:55+00:00,671973,268436137,268435460,47.495600,-0.569680,BEAUCOUZE <> ST BARTHELEMY,SORTIE BUS CTB,04,OmniArtE6
1,PAS EN SERVICE,0,HLPS,2018-06-19T07:09:46+00:00,671375,268436259,268435460,47.476323,-0.492809,BEAUCOUZE <> ST BARTHELEMY,SORTIE DEPOT ST BART,04,OmniSTDE6
2,PAS EN SERVICE,0,HLPS,2018-06-19T07:26:00+00:00,671375,268435899,268435462,47.475119,-0.492731,BOUCHEMAINE <> Z I EST,SORTIE DEPOT ST BART,06,OMNICITY
3,PAS EN SERVICE,0,HLPS,2018-06-19T07:45:09+00:00,671973,268436120,268435457,47.495681,-0.569286,BELLE BEILLE <> MONPLAISIR,SORTIE BUS CTB,01,OMNIART
4,AQUAVITA VERNEAU,0,TDEP,2018-06-19T09:14:00+00:00,671784,268435910,268435464,47.433765,-0.500644,PONTS CE <> AQUAVITA H. RECULEE,MOULIN MARCILLE,08,OMNICITY
5,CIRCULAIRE SENS B,0,TDEP,2018-06-19T09:21:00+00:00,672581,268435913,268435461,47.493159,-0.565430,CIRCULAIRE VERNEAU GARE EUROPE,AQUA VITA,05,OMNICITY
6,MONPLAISIR,0,TDEP,2018-06-19T09:18:00+00:00,671723,268436057,268435457,47.478642,-0.605691,BELLE BEILLE <> MONPLAISIR,MAISON DE TECHNOPOLE,01,MAN City
7,SPECIAL PISCINE,-247,HL,2018-06-19T09:30:00+00:00,672636,268435879,268435515,47.476644,-0.507283,Piscine MONPLAISIR,PISCINE MONPLAISIR,535,OMNICITY
8,MOULIN MARCILLE PAR TRELA,235,LIGN,2018-06-19T09:13:46+00:00,671760,268435905,268435468,47.472719,-0.530305,M-MARCILLE <> ST AUBIN LA SALLE,MONTAIGNE,12,OMNICITY
9,MOULIN MARCILLE PAR TRELA,6,LIGN,2018-06-19T09:14:13+00:00,671915,268435909,268435468,47.452054,-0.507642,M-MARCILLE <> ST AUBIN LA SALLE,REPUBLIQUE TRELAZE,12,OMNICITY

In [9]:
# df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 13 columns):
dest        10 non-null object
ecart       10 non-null object
etat        10 non-null object
harret      10 non-null object
idArret     10 non-null object
idBus       10 non-null object
idLigne     10 non-null object
lats        10 non-null float64
lons        10 non-null float64
nomLigne    10 non-null object
nomarret    10 non-null object
numLigne    10 non-null object
type        10 non-null object
dtypes: float64(2), object(11)
memory usage: 1.1+ KB

In [10]:
# ouverture de la connection vers la bdd
engine = create_engine("sqlite:///data.sqlite")
connection = engine.connect()

In [11]:
# bus
dft = df[['idBus', 'type', 'etat']]
print(dft)

       idBus       type  etat
0  268436137  OmniArtE6  HLPS
1  268436259  OmniSTDE6  HLPS
2  268435899   OMNICITY  HLPS
3  268436120    OMNIART  HLPS
4  268435910   OMNICITY  TDEP
5  268435913   OMNICITY  TDEP
6  268436057   MAN City  TDEP
7  268435879   OMNICITY    HL
8  268435905   OMNICITY  LIGN
9  268435909   OMNICITY  LIGN

In [12]:
assert not df['idBus'].isnull().any()

In [13]:
# export dans SQL
dft.to_sql('bus', connection, if_exists='replace', index=False)

In [14]:
# arret
dft = df[['idArret', 'nomarret']]
print(dft)

  idArret              nomarret
0  671973        SORTIE BUS CTB
1  671375  SORTIE DEPOT ST BART
2  671375  SORTIE DEPOT ST BART
3  671973        SORTIE BUS CTB
4  671784       MOULIN MARCILLE
5  672581             AQUA VITA
6  671723  MAISON DE TECHNOPOLE
7  672636    PISCINE MONPLAISIR
8  671760             MONTAIGNE
9  671915    REPUBLIQUE TRELAZE

In [15]:
# export dans SQL
dft.to_sql('arret', connection, if_exists='replace', index=False)

In [16]:
# ligne
dft = df[['idLigne', 'nomLigne', 'numLigne']]
print(dft)

     idLigne                          nomLigne numLigne
0  268435460        BEAUCOUZE <> ST BARTHELEMY       04
1  268435460        BEAUCOUZE <> ST BARTHELEMY       04
2  268435462           BOUCHEMAINE <> Z I  EST       06
3  268435457        BELLE BEILLE <> MONPLAISIR       01
4  268435464  PONTS CE <>  AQUAVITA H. RECULEE       08
5  268435461    CIRCULAIRE VERNEAU GARE EUROPE       05
6  268435457        BELLE BEILLE <> MONPLAISIR       01
7  268435515                Piscine MONPLAISIR      535
8  268435468   M-MARCILLE <> ST AUBIN LA SALLE       12
9  268435468   M-MARCILLE <> ST AUBIN LA SALLE       12

In [17]:
# export dans SQL
dft.to_sql('ligne', connection, if_exists='replace', index=False)

In [29]:
# trajet
dft = df[['idBus', 'idLigne', 'lats', 'lons', 'dest']]
print(dft)

       idBus    idLigne       lats      lons                       dest
0  268436137  268435460  47.495600 -0.569680             PAS EN SERVICE
1  268436259  268435460  47.476323 -0.492809             PAS EN SERVICE
2  268435899  268435462  47.475119 -0.492731             PAS EN SERVICE
3  268436120  268435457  47.495681 -0.569286             PAS EN SERVICE
4  268435910  268435464  47.433765 -0.500644           AQUAVITA VERNEAU
5  268435913  268435461  47.493159 -0.565430          CIRCULAIRE SENS B
6  268436057  268435457  47.478642 -0.605691                 MONPLAISIR
7  268435879  268435515  47.476644 -0.507283            SPECIAL PISCINE
8  268435905  268435468  47.472719 -0.530305  MOULIN MARCILLE PAR TRELA
9  268435909  268435468  47.452054 -0.507642  MOULIN MARCILLE PAR TRELA

In [19]:
# export dans SQL
dft.to_sql('trajet', connection, if_exists='replace', index=False)

In [20]:
# conversion harret
df['harret'] = pd.to_datetime(df['harret'], format='%Y-%m-%d %H:%M:%S.%f')
print(df[['harret']])

               harret
0 2018-06-19 06:53:55
1 2018-06-19 07:09:46
2 2018-06-19 07:26:00
3 2018-06-19 07:45:09
4 2018-06-19 09:14:00
5 2018-06-19 09:21:00
6 2018-06-19 09:18:00
7 2018-06-19 09:30:00
8 2018-06-19 09:13:46
9 2018-06-19 09:14:13

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7    -247
8     235
9       6
Name: ecart, dtype: object

In [27]:
# convertir ecart en int
df['ecart'] = df['ecart'].astype(int)

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7   -247
8    235
9      6
Name: ecart, dtype: int32

In [28]:
# conversion ecart
# df['ecart'] = pd.to_datetime(df['ecart'], format='%S.%f')
# for c in df['ecart']:
#     if c != 0:
#         pd.to_datetime(c, format='%S.%f')

# print(c)

In [ ]:
# étape
dft = df[['idBus', 'idArret', 'harret', 'ecart']]
print(dft)

In [ ]:
# export dans SQL
dft.to_sql('etape', connection, if_exists='replace', index=False)

In [ ]:
connection.close()